name: Semgrep Security Scan

on:
  push:
    branches:
    - develop
    - prueba-semgrep 
    pull_request:
      branches:
      - develop

jobs:
  semgrep:
    name: Semgrep Analysis
    runs-on: ubuntu-latest


    container:
      image: semgrep/semgrep

    steps:
     - name: Descargar repositorio
       uses: actions/checkout@v4

     - name: Ejecutar Semgrep
       run: semgrep scan --config=auto --error .


